### ISSUE TITLE
I think you mean  'new_resource' here

### ISSUE THREAD

**Issue by gerard76** [chef-cookbooks/remote_install#18]
i got the error:
```
NameError: remote_install_remote_install[ImageMagick] (eetnu::heic line 26) had an error: NameError: undefined local variable or method `resource' for #<#<Class:0x0000000003aaa688>:0x0000000003d7d4c8>
/var/chef/cache/cookbooks/remote_install/resources/remote_install.rb:89:in `verify'
/var/chef/cache/cookbooks/remote_install/resources/remote_install.rb:35:in `block (2 levels) in class_from_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/provider.rb:227:in `converge_by'
/var/chef/cache/cookbooks/remote_install/resources/remote_install.rb:33:in `block in class_from_file'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/provider.rb:236:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_install'
```

https://github.com/chef-cookbooks/remote_install/blob/d9555a53cba20667b3d463d04e18dc2a42f45b9d/resources/remote_install.rb#L89

**Comment by tas50** [comment]
Fixed up thanks to @eirvandelden
